spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 172.23.238.198:9092
      bindings:
        show-scheduler-in:
          destination: UpdatedMovieEvent
          contentType: application/json
        show-scheduler-out:
          destination: UpdatedMovieEvent
          contentType: application/json