spring:
  data:
     mongodb:
        uri: mongodb://0.0.0.0:27000/test
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        rsvp-event-in:
          destination: RSVPEvent
          contentType: application/json
        rsvp-event-out:
          destination: RSVPEvent
          contentType: application/json

