spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 172.23.238.170:9092
      bindings:
        rsvp-event-in:
          destination: RSVPEvent
          contentType: application/json
        rsvp-event-out:
          destination: RSVPEvent
          contentType: application/json
# data: 
#  mongodb:
#   port: 27017
#   host: localhost
#   database: test
#   uri: mongodb://172.23.238.255:27017/user_movie
# data:
#      mongodb:
#         uri: mongodb://172.23.238.255:27000/test

server:
 port: 8092