spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 172.23.238.170:9092
      bindings:
        user-registration-out:
          destination: User
          contentType: application/json
        theatre-in:
          destination: Theatre
          contentType: application/json
        rsvp-event-in:
          destination: RSVPEvent
          contentType: application/json