spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        user-registration-out:
          destination: User
          contentType: application/json