spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        movie-event-out:
          destination: MovieEvent
          contentType: application/json
        RSVP-event-out: 
          destination: RSVPEvent
          contentType: application/json
        ticketed-event-out:
          destination: TicketedEvent
          contentType: application/json
        theatre-out  :
          destination: Theatre
          contentType: application/json
        movie-out    :
          destination: Movie
          contentType: application/json
